---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    toolkit.fluxcd.io/tenant: auth
    istio-injection: enabled
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-auth
  namespace: flux-system
spec:
  sourceRef:
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: operators
    - name: controllers
  interval: 5m
  path: ./base/apps-auth
  prune: true
