---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-dev
  namespace: flux-system
spec:
  sourceRef:
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: operators
    - name: controllers
  interval: 5m
  path: ./clusters/home-k8s/apps-dev
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-infra
  namespace: flux-system
spec:
  sourceRef:
    apiVersion: source.toolkit.fluxcd.io/v1
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: operators
    - name: controllers
  interval: 5m
  path: ./clusters/home-k8s/apps-infra
  prune: true
