---
apiVersion: v1
kind: Namespace
metadata:
  name: service-capture
  labels:
    toolkit.fluxcd.io/tenant: app
    istio-injection: enabled
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: service-cap
  namespace: service-cap
spec:
  interval: 1m0s
  url: https://github.com/PolecatWorks/service-capture.git
  ref:
    branch: main
  # secretRef:
  #   name: service-capture-git
# Check token is valid
# curl -sS -f -I -H "Authorization: ${FLUX_POLECATWORKS_GITHUB_TOKEN}" https://api.github.com
# kubectl -n service-capture create secret generic service-capture-git --from-literna=username=git --from-literal=password="${FLUX_POLECATWORKS_GITHUB_TOKEN}"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: service-capture
  namespace: service-cap
spec:
  interval: 10m0s
  path: ./fluxcd-dev
  targetNamespace: service-cap
  prune: true
  sourceRef:
    kind: GitRepository
    name: service-cap
