---
apiVersion: v1
kind: Namespace
metadata:
  name: service-cap
  labels:
    toolkit.fluxcd.io/tenant: app
    istio-injection: enabled
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: k8s-store-service-cap-ns
  namespace: dbs
spec:
  provider:
    kubernetes:
      remoteNamespace: service-cap  # The destination
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: sa-externalsecret  # ServiceAccount in 'dbs' namespace with permissions to read secrets in target namespaces
---
# Push the DB cred to allow the service-cap app to access the DB
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-db0-service-cap-user-to-service-cap-ns
  namespace: dbs
spec:
  refreshInterval: 1m0s
  updatePolicy: Replace # Pushes and overwrites immediately
  deletionPolicy: Delete # Deletes from provider when PushSecret is gone
  secretStoreRefs:
    - name: k8s-store-service-cap-ns
      kind: SecretStore
  selector:
    secret:
      name: db0-service-cap-user # The source secret in 'dbs'
  template:
    type: kubernetes.io/dockerconfigjson
  data:
    - match:
        secretKey: username # The source secret key in secret in 'dbs' namespace
        remoteRef:
          remoteKey: db0-service-cap-user # name of the target secret in the auth namespace
          property: username # The key in the target secret
    - match:
        secretKey: password
        remoteRef:
          remoteKey: db0-service-cap-user # Must match the one above to put both in one secret
          property: password
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: service-cap
  namespace: service-cap
spec:
  interval: 1m0s
  url: https://github.com/PolecatWorks/service-capture.git
  ref:
    branch: main
  # secretRef:
  #   name: service-capture-git
# Check token is valid
# curl -sS -f -I -H "Authorization: ${FLUX_POLECATWORKS_GITHUB_TOKEN}" https://api.github.com
# kubectl -n service-capture create secret generic service-capture-git --from-literna=username=git --from-literal=password="${FLUX_POLECATWORKS_GITHUB_TOKEN}"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: service-cap
  namespace: service-cap
spec:
  interval: 10m0s
  path: ./fluxcd-dev
  targetNamespace: service-cap
  prune: true
  sourceRef:
    kind: GitRepository
    name: service-cap
