---
# Setup from dbs to service-cap
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: k8s-store-service-cap-ns
  namespace: dbs
spec:
  provider:
    kubernetes:
      remoteNamespace: service-cap  # The destination
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: sa-externalsecret  # ServiceAccount in 'dbs' namespace with permissions to read secrets in target namespaces
---
# Push the DB cred to allow the service-cap app to access the DB
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-db0-service-cap-user-to-service-cap-ns
  namespace: dbs
spec:
  refreshInterval: 1m0s
  updatePolicy: Replace # Pushes and overwrites immediately
  deletionPolicy: Delete # Deletes from provider when PushSecret is gone
  secretStoreRefs:
    - name: k8s-store-service-cap-ns
      kind: SecretStore
  selector:
    secret:
      name: db0-service-cap-user # The source secret in 'dbs'
  # template:
  #   type: kubernetes.io/dockerconfigjson
  data:
    - match:
        secretKey: username # The source secret key in secret in 'dbs' namespace
        remoteRef:
          remoteKey: db0-service-cap-user # name of the target secret in the auth namespace
          property: username # The key in the target secret
    - match:
        secretKey: password
        remoteRef:
          remoteKey: db0-service-cap-user # Must match the one above to put both in one secret
          property: password
---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealm
metadata:
  name: dev
  namespace: auth
spec:
  realmName: dev
  keycloakRef:
    kind: Keycloak
    name: keycloak
  displayName: Dev for Service Capture
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-dev-sa-secret
  namespace: dev
spec:
  refreshInterval: 1h
  target:
    template:
      data:
        username: dev-admin-sa
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: keycloak-password
---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: dev-admin-sa
  namespace: auth
spec:
  clientId: dev-admin-sa
  name: Dev Admin Service Account
  realmRef:
    name: master
    kind: KeycloakRealm
  secret: $keycloak-dev-sa-secret:password
  public: false
  protocol: openid-connect
  serviceAccount:
    enabled: true
    realmRoles:
      - offline_access
      - admin
    clientRoles:
      - clientId: master-realm
        roles:
          - manage-realm

# # Keycloak realm for service-cap
# apiVersion: external-secrets.io/v1
# kind: SecretStore
# metadata:
#   name: keycloak-service_cap_realm-ca
#   namespace: auth
# spec:
#   provider:
#     kubernetes:
#       remoteNamespace: service-cap  # The destination
#       server:
#         url: https://kubernetes.default.svc
#         caProvider:
#           type: ConfigMap
#           name: kube-root-ca.crt
#           key: ca.crt
#       auth:
#         serviceAccount:
#           name: sa-externalsecret  # ServiceAccount in 'dbs' namespace with permissions to read secrets in target namespaces
# ---
# # Push the realm cred to allow the service-cap app to access the DB
# apiVersion: external-secrets.io/v1alpha1
# kind: PushSecret
# metadata:
#   name: push-db0-service-cap-user-to-service-cap-ns
#   namespace: dbs
# spec:
#   refreshInterval: 1m0s
#   updatePolicy: Replace # Pushes and overwrites immediately
#   deletionPolicy: Delete # Deletes from provider when PushSecret is gone
#   secretStoreRefs:
#     - name: k8s-store-service-cap-ns
#       kind: SecretStore
#   selector:
#     secret:
#       name: db0-service-cap-user # The source secret in 'dbs'
#   # template:
#   #   type: kubernetes.io/dockerconfigjson
#   data:
#     - match:
#         secretKey: username # The source secret key in secret in 'dbs' namespace
#         remoteRef:
#           remoteKey: db0-service-cap-user # name of the target secret in the auth namespace
#           property: username # The key in the target secret
#     - match:
#         secretKey: password
#         remoteRef:
#           remoteKey: db0-service-cap-user # Must match the one above to put both in one secret
#           property: password
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: service-cap
  namespace: dev
spec:
  interval: 1m0s
  url: https://github.com/PolecatWorks/service-capture.git
  ref:
    branch: main
  # secretRef:
  #   name: service-capture-git
# Check token is valid
# curl -sS -f -I -H "Authorization: ${FLUX_POLECATWORKS_GITHUB_TOKEN}" https://api.github.com
# kubectl -n service-capture create secret generic service-capture-git --from-literna=username=git --from-literal=password="${FLUX_POLECATWORKS_GITHUB_TOKEN}"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: service-cap
  namespace: dev
spec:
  interval: 10m0s
  path: ./fluxcd-dev
  targetNamespace: dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: service-cap
