---
# kubectl -n dbs create secret generic mysql-access --from-literal=user=root --from-literal=password=myrootpw --from-literal=mysql-password=mypw --from-literal=mysql-root-password=myrootpw
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mysql
spec:
  releaseName: mysql
  chart:
    spec:
      chart: mysql
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bitnami
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    auth:
      existingSecret: mysql-access
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        labels:
          release: prometheus-stack
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: phpmyadmin
spec:
  releaseName: phpmyadmin
  timeout: 10m
  install:
    remediation:
      retries: 3
  chart:
    spec:
      chart: phpmyadmin
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bitnami
  interval: 50m
  values: {}
---
# create a DBInstance pointing to my mysql instance
apiVersion: kinda.rocks/v1beta1
kind: DbInstance
metadata:
  name: mysql-instance
  # cluster-scoped resource, no namespace
spec:
  adminSecretRef:
    Name: mysql-access # reference secret created by previous command
    Namespace: dbs
  engine: mysql
  generic:
    host: "mysql.dbs.svc.cluster.local"
    port: 3306 # default mysql port
