---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bview0
spec:
  releaseName: bview0
  chart:
    spec:
      chart: bucket-view/helm/nginx-view
      version: 0.0.0
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: polecatworks
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    imagePullSecrets:
      - name: dockerconfigjson-ghcr-io
    image:
      repository: ghcr.io/polecatworks/bucket-view
      tag: main
      pullPolicy: Always
    # schema:
    #   image: *image
