---
apiVersion: v1
kind: Namespace
metadata:
  name: cnpg-operator
  labels:
    toolkit.fluxcd.io/tenant: dbs
    istio-injection: disabled
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cnpg
  namespace: cnpg-operator
spec:
  interval: 60m
  url: https://cloudnative-pg.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cnpg-operator
  namespace: cnpg-operator
spec:
  releaseName: cnpg-operator
  chart:
    spec:
      chart: cloudnative-pg
      sourceRef:
        kind: HelmRepository
        name: cnpg
  interval: 50m
  values:
    config:
      clusterWide: true
      data:
        WATCH_NAMESPACE: dbs
