---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-ghcr-docker-auth-to-sward-warden-dev-ns
  namespace: auth
spec:
  refreshInterval: 1m0s
  updatePolicy: Replace
  deletionPolicy: Delete
  secretStoreRefs:
    - name: push-secrets-to-sward-warden-dev-ns
      kind: SecretStore
  selector:
    secret:
      name: ghcr-docker-auth
  template:
    type: kubernetes.io/dockerconfigjson
  data:
    - match:
        secretKey: .dockerconfigjson
        remoteRef:
          remoteKey: ghcr-docker-auth
          property: .dockerconfigjson
