---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-master-0-sa-secret
  namespace: auth
spec:
  refreshInterval: 1h
  refreshPolicy: CreatedOnce
  target:
    template:
      data:
        username: master-admin-0-sa
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: keycloak-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-master-1-sa-secret
  namespace: auth
spec:
  refreshInterval: 1h
  refreshPolicy: CreatedOnce
  target:
    template:
      data:
        username: master-admin-1-sa
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: keycloak-password
---
apiVersion: v1.edp.epam.com/v1
kind: Keycloak
metadata:
  name: keycloak
  namespace: auth
spec:
  adminType: serviceAccount
  secret: keycloak-master-sa-secret             # Secret name
  url: http://keycloak-keycloakx-http.auth.svc.cluster.local/auth   # Keycloak URL
---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealm
metadata:
  name: master
  namespace: auth
spec:
  realmName: master
  keycloakRef:
    kind: Keycloak
    name: keycloak
---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: master-admin-0-sa
  namespace: auth
spec:
  clientId: master-admin-0-sa
  name: Master Admin Service Account
  realmRef:
    name: master
    kind: KeycloakRealm
  secret: $keycloak-master-sa-secret:password
  public: false
  protocol: openid-connect
  serviceAccount:
    enabled: true
    realmRoles:
      - offline_access
      - admin
    clientRoles:
      - clientId: master-realm
        roles:
          - manage-realm
---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: master-admin-1-sa
  namespace: auth
spec:
  clientId: master-admin-1-sa
  name: Master Admin Service Account
  realmRef:
    name: master
    kind: KeycloakRealm
  secret: $keycloak-master-1-sa-secret:password
  public: false
  protocol: openid-connect
  serviceAccount:
    enabled: true
    realmRoles:
      - offline_access
      - admin
    clientRoles:
      - clientId: master-realm
        roles:
          - manage-realm
