---
# Push the DB cred to allow the service-cap app to access the DB
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-db0-recon-user-to-dev-ns
  namespace: dbs
spec:
  refreshInterval: 1m0s
  updatePolicy: Replace # Pushes and overwrites immediately
  deletionPolicy: Delete # Deletes from provider when PushSecret is gone
  secretStoreRefs:
    - name: push-secrets-to-dev-ns
      kind: SecretStore
  selector:
    secret:
      name: db0-recon-user # The source secret in 'dbs'
  # template:
  #   type: kubernetes.io/dockerconfigjson
  data:
    - match:
        secretKey: username # The source secret key in secret in 'dbs' namespace
        remoteRef:
          remoteKey: db0-recon-user # name of the target secret in the auth namespace
          property: username # The key in the target secret
    - match:
        secretKey: password
        remoteRef:
          remoteKey: db0-recon-user # Must match the one above to put both in one secret
          property: password
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: input
  namespace: confluent
spec:
  kafkaClusterRef:
    name: kafka
    namespace: confluent
  replicas: 3
  partitionCount: 79
  configs:
    cleanup.policy: delete
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: recon-dev
  namespace: dev
spec:
  interval: 1m0s
  url: https://github.com/PolecatWorks/k8s-micro.git
  ref:
    branch: main
  # secretRef:
  #   name: service-capture-git
# Check token is valid
# curl -sS -f -I -H "Authorization: ${FLUX_POLECATWORKS_GITHUB_TOKEN}" https://api.github.com
# kubectl -n service-capture create secret generic service-capture-git --from-literna=username=git --from-literal=password="${FLUX_POLECATWORKS_GITHUB_TOKEN}"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: recon-dev
  namespace: dev
spec:
  interval: 10m0s
  path: ./fluxcd-dev
  targetNamespace: dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: recon-dev
