---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealm
metadata:
  name: dev
  namespace: auth
spec:
  realmName: dev
  keycloakRef:
    kind: Keycloak
    name: keycloak
  displayName: Realm for dev environment
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: keycloak-password
  namespace: dev
spec:
  length: 32
  symbols: 0
  allowRepeat: true
  noUpper: false
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-dev-sa
  namespace: auth
spec:
  refreshInterval: 1h
  target:
    template:
      data:
        username: dev-admin-sa
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: keycloak-password
---
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: dev-admin-sa
  namespace: auth
spec:
  clientId: dev-admin-sa
  name: Dev Admin Service Account
  realmRef:
    name: dev
    kind: KeycloakRealm
  secret: $keycloak-dev-sa:password
  public: false
  protocol: openid-connect
  serviceAccount:
    enabled: true
    realmRoles:
      - offline_access
      - admin
    clientRoles:
      - clientId: dev-realm
        roles:
          - manage-realm
---
# Push the realm cred to allow the service-cap app to access the DB
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-keycloak-dev-sa-to-dev-ns
  namespace: auth
spec:
  refreshInterval: 1m0s
  updatePolicy: Replace # Pushes and overwrites immediately
  deletionPolicy: Delete # Deletes from provider when PushSecret is gone
  secretStoreRefs:
    - name: k8s-store-dev-ns
      kind: SecretStore
  selector:
    secret:
      name: keycloak-dev-sa-secret # The source secret in 'dbs'
  # template:
  #   type: kubernetes.io/dockerconfigjson
  data:
    - match:
        secretKey: username # The source secret key in secret in 'dbs' namespace
        remoteRef:
          remoteKey: k8s-store-dev-ns # name of the target secret in the auth namespace
          property: username # The key in the target secret
    - match:
        secretKey: password
        remoteRef:
          remoteKey: k8s-store-dev-ns # Must match the one above to put both in one secret
          property: password
