---
# Before this can become active you need to create the dev realm in Keycloak.
# Once it is created then this set of CRDs will manage it.
# Setup Keycloak and Keycloak Realm in the dev namespace
apiVersion: v1.edp.epam.com/v1
kind: Keycloak
metadata:
  name: keycloak-dev
  namespace: dev
spec:
  adminType: serviceAccount
  secret: keycloak-dev-sa            # Secret name
  url: http://keycloak-keycloakx-http.auth.svc.cluster.local/auth   # Keycloak URL
---
# Create the dev keycloak realm. This is locked to the auth namespace to ensure develpers cannot access it directly (it is platform owned)
apiVersion: v1.edp.epam.com/v1
kind: KeycloakRealm
metadata:
  name: dev
  namespace: dev
spec:
  realmName: dev
  keycloakRef:
    kind: Keycloak
    name: keycloak-dev
  displayName: Realm for dev environment
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-dev-sa
  namespace: auth
spec:
  refreshInterval: 1h
  refreshPolicy: CreatedOnce
  target:
    template:
      data:
        username: dev-admin-sa
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: keycloak-password
---
# Create a service account client in the auth ns to manage the dev realm
apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: dev-admin-sa
  namespace: auth
spec:
  clientId: dev-admin-sa
  name: Dev Admin Service Account
  realmRef:
    name: master
    kind: KeycloakRealm
  secret: $keycloak-dev-sa:password
  public: false
  protocol: openid-connect
  serviceAccount:
    enabled: true
    # realmRoles:
    #   - manage-realm
    clientRoles:
      - clientId: dev-realm
        roles:
          - manage-realm
          - manage-clients
          - manage-events
---
# Push the realm cred to allow the dev namespace to use it
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-keycloak-dev-sa-to-dev-ns
  namespace: auth
spec:
  refreshInterval: 1m0s
  updatePolicy: Replace # Pushes and overwrites immediately
  deletionPolicy: Delete # Deletes from provider when PushSecret is gone
  secretStoreRefs:
    - name: push-secrets-to-dev-ns
      kind: SecretStore
  selector:
    secret:
      name: keycloak-dev-sa # The source secret
  # template:
  #   type: kubernetes.io/dockerconfigjson
  data:
    - match:
        secretKey: username # The source secret key
        remoteRef:
          remoteKey: keycloak-dev-sa # name of the target secret
          property: username # The key in the target secret
    - match:
        secretKey: password
        remoteRef:
          remoteKey: keycloak-dev-sa # Must match the one above to put both in one secret
          property: password
---
# This is not allowed in this operator as realmName must be unique across the cluster
# apiVersion: v1.edp.epam.com/v1
# kind: KeycloakRealm
# metadata:
#   name: dev-realm-link
#   namespace: dev
# spec:
#   realmName: dev
#   keycloakRef:
#     kind: Keycloak
#     name: keycloak-dev
