---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: mfe-shell
  namespace: dev
spec:
  interval: 1m0s
  url: https://github.com/PolecatWorks/mfe-shell.git
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mfe-shell
  namespace: dev
spec:
  interval: 10m0s
  path: ./fluxcd-dev
  targetNamespace: dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: mfe-shell
