---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaTopic
metadata:
  name: pcache-users
  namespace: confluent
spec:
  kafkaClusterRef:
    name: kafka
    namespace: confluent
  replicas: 3
  partitionCount: 17
  configs:
    cleanup.policy: delete
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: push-cache
  namespace: dev
spec:
  interval: 1m0s
  url: https://github.com/PolecatWorks/push-cache.git
  ref:
    branch: main
  # secretRef:
  #   name: service-capture-git
# Check token is valid
# curl -sS -f -I -H "Authorization: ${FLUX_POLECATWORKS_GITHUB_TOKEN}" https://api.github.com
# kubectl -n service-capture create secret generic service-capture-git --from-literna=username=git --from-literal=password="${FLUX_POLECATWORKS_GITHUB_TOKEN}"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: push-cache
  namespace: dev
spec:
  interval: 10m0s
  path: ./fluxcd-dev
  targetNamespace: dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: push-cache
