---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kiali-server
  namespace: istio-system
spec:
  releaseName: kiali-server
  chart:
    spec:
      chart: kiali-server
      version: 1.85.*
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: kiali
  interval: 50m
  install:
    remediation:
      retries: 3
  values: {}
