---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-store-push-role
  namespace: keycloak-operator # Destination namespace where the secret will be pushed
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-eso-store-role-to-eso-service-account
  namespace: keycloak-operator # Destination namespace where the secret will be pushed
subjects:
  - kind: ServiceAccount
    name: sa-externalsecret
    namespace: auth
roleRef:
  kind: Role
  name: eso-store-push-role
  apiGroup: rbac.authorization.k8s.io
