---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - secret-store.yaml
  - secrets.yaml
  - deployment.yaml
  - auth_send_push_secrets
  - dbs_send_push_secrets
  - dev_enable_receive_secrets
  - dev_receive_secrets_from_auth
  - dev_receive_secrets_from_dbs
