---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: push-secrets-to-sward-warden-dev-ns
  namespace: dbs
spec:
  provider:
    kubernetes:
      remoteNamespace: sward-warden-dev
      server:
        url: https://kubernetes.default.svc
      auth:
        serviceAccount:
          name: sa-externalsecret
