---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-db0-sward-warden-user
spec:
  refreshInterval: 1m0s
  updatePolicy: Replace
  deletionPolicy: Delete
  secretStoreRefs:
    - name: push-secrets-to
      kind: SecretStore
  selector:
    secret:
      name: db0-sward-warden-user
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: db0-sward-warden-user
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: db0-sward-warden-user
          property: password
