# Create the secret manually in the agent-as-data-dev namespace if private:
# kubectl create secret generic aad-gh-pat -n agent-as-data-dev --from-literal=username=<USER> --from-literal=password=<PAT>
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: agent-as-data
  namespace: agent-as-data-dev
spec:
  interval: 1m0s
  url: https://github.com/PolecatWorks/agent-as-data.git
  secretRef:
    name: aad-gh-pat
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: agent-as-data
  namespace: agent-as-data-dev
spec:
  interval: 10m0s
  path: ./fluxcd-dev
  targetNamespace: agent-as-data-dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: agent-as-data
