---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-realm-agent-as-data
  namespace: auth
spec:
  refreshInterval: 1m0s
  updatePolicy: Replace
  deletionPolicy: Delete
  secretStoreRefs:
    - name: push-secrets-to-agent-as-data-dev-ns
      kind: SecretStore
  selector:
    secret:
      name: keycloak-aad-dev-sa
  data:
    - match:
        secretKey: username
        remoteRef:
          remoteKey: keycloak-aad-dev-sa
          property: username
    - match:
        secretKey: password
        remoteRef:
          remoteKey: keycloak-aad-dev-sa
          property: password
