# Following guide at: https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/quickstart-deploy
# and this guide: https://docs.confluent.io/operator/current/co-quickstart.html
---
apiVersion: v1
kind: Namespace
metadata:
  name: confluent
  labels:
    toolkit.fluxcd.io/tenant: persistence
---
apiVersion: platform.confluent.io/v1beta1
kind: KRaftController
metadata:
  name: kraftcontroller
  namespace: confluent
spec:
  dataVolumeCapacity: 10G
  storageClass:
    name: longhorn-single
  image:
    application: docker.io/confluentinc/cp-server:7.9.1
    init: confluentinc/confluent-init-container:2.11.1
  replicas: 3
  clusterID: MzY5NTAwZWQtYTJjMy00Zg
---
apiVersion: platform.confluent.io/v1beta1
kind: Kafka
metadata:
  name: kafka
  namespace: confluent
spec:
  dependencies:
    kRaftController:
      clusterRef:
        name: kraftcontroller
  dataVolumeCapacity: 10G
  storageClass:
    name: longhorn-single
  image:
    application: docker.io/confluentinc/cp-server:7.9.1
    init: confluentinc/confluent-init-container:2.11.1
  replicas: 3
---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-server-connect:7.9.1
    init: confluentinc/confluent-init-container:2.11.1
  dependencies:
    kafka:
      bootstrapEndpoint: kafka:9071
---
apiVersion: platform.confluent.io/v1beta1
kind: KsqlDB
metadata:
  name: ksqldb
  namespace: confluent
spec:
  replicas: 1
  image:
    application: confluentinc/cp-ksqldb-server:7.9.1
    init: confluentinc/confluent-init-container:2.11.1
  dataVolumeCapacity: 10Gi
  storageClass:
    name: longhorn-single
---
apiVersion: platform.confluent.io/v1beta1
kind: ControlCenter
metadata:
  name: controlcenter
  namespace: confluent
spec:
  replicas: 2
  podTemplate:
    probe:
      liveness:
        initialDelaySeconds: 360
  image:
    application: confluentinc/cp-enterprise-control-center:7.9.1
    init: confluentinc/confluent-init-container:2.11.1
  dataVolumeCapacity: 10Gi
  storageClass:
    name: longhorn-single
  dependencies:
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
    kafka:
      bootstrapEndpoint: http://kafka.confluent.svc.cluster.local:9071
    ksqldb:
    - name: ksqldb
      url: http://ksqldb.confluent.svc.cluster.local:8088
    connect:
    - name: connect
      url: http://connect.confluent.svc.cluster.local:8083

    # ksqldb:
    # - name: ksqldb
    #   url: http://ksqldb.confluent.svc.cluster.local:8088
    # connect:
    # - name: connect
    #   url: http://connect.confluent.svc.cluster.local:8083
---
apiVersion: platform.confluent.io/v1beta1
kind: SchemaRegistry
metadata:
  name: schemaregistry
  namespace: confluent
spec:
  replicas: 2
  image:
    application: confluentinc/cp-schema-registry:7.9.1
    init: confluentinc/confluent-init-container:2.11.1
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestProxy
metadata:
  name: kafkarestproxy
  namespace: confluent
spec:
  replicas: 2
  image:
    application: confluentinc/cp-kafka-rest:7.9.1
    init: confluentinc/confluent-init-container:2.11.1
  dependencies:
    schemaRegistry:
      url: http://schemaregistry.confluent.svc.cluster.local:8081
---
apiVersion: platform.confluent.io/v1beta1
kind: KafkaRestClass
metadata:
  name: krc-cfk
  namespace: confluent
spec:
  kafkaClusterRef:
    name: kafka
  kafkaRest:
    endpoint: http://kafka.confluent.svc.cluster.local:8090
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: controlcenter
  namespace: confluent
spec:
  hosts:
  - controlcenter.k8s
  gateways:
  - istio-ingress/k8s-gateway
  - mesh # applies to all the sidecars in the mesh
  http:
  - route:
    - destination:
        host: controlcenter.confluent.svc.cluster.local
        port:
          number: 9021
