---
apiVersion: v1
kind: Namespace
metadata:
  name: ollama
  labels:
    toolkit.fluxcd.io/tenant: llm
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: otwld
  namespace: ollama
spec:
  interval: 60m
  url: https://helm.otwld.com/
---
# helm install ollama otwld/ollama --namespace ollama --create-namespace
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ollama
  namespace: ollama
spec:
  releaseName: ollama
  chart:
    spec:
      chart: ollama
      sourceRef:
        kind: HelmRepository
        name: otwld
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    image:
      tag: latest
    ollama:
      gpu:
        enabled: false
      models:
        pull:
          - qwen2.5-coder:14b
    resources:
      requests:
        memory: 16Gi
        cpu: 2
      # limits:
      #   memory: 8Gi
      #   cpu: 4
    persistentVolume:
      enabled: true
      storageClass: longhorn-single
      size: 20Gi
