---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8s-python-cake
spec:
  releaseName: cake
  chart:
    spec:
      chart: helm-charts/k8s-python
      version: 0.0.0
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: polecatworks
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    webservice:
      prefix: cake/v0
    imagePullSecrets:
      - name: dockerconfigjson-ghcr-io
    image:
      repository: ghcr.io/polecatworks/k8s-python
      tag: main
      pullPolicy: Always
    devsecops:
      RequestAuthentication:
        jwtRules:
          - issuer: http://dev.k8s/auth/realms/dev
            jwksUri: http://keycloak.security/auth/realms/dev/protocol/openid-connect/certs
            forwardOriginalToken: true
            audiences:
              - app-cake
      AuthorizationPolicy:
        rules:
        - to:
          - operation:
              methods:
              - GET
              paths:
              - /cake/v0/chunks
          when:
          - key: request.auth.claims[resource_access][app-pie][roles]
            values:
            - chunks-read
        - to:
          - operation:
              methods:
              - POST
              - PUT
              paths:
              - /cake/v0/chunks
          when:
          - key: request.auth.claims[resource_access][app-pie][roles]
            values:
            - chunks-write
