
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: dummy-name
  # namespace: auth
spec:
  provider:
    kubernetes:
      # remoteNamespace: keycloak-operator  # The destination
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: sa-externalsecret  # ServiceAccount in 'dbs' namespace with permissions to read secrets in 'auth' namespace
