---
# Create role and rolebinding to allow external-secrets to push secrets to keycloak-operator namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eso-store-push-role
  # namespace: keycloak-operator # Destination namespace where the secret will be pushed. to be provided by Kustomize
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - authorization.k8s.io
  resources:
  - selfsubjectrulesreviews
  verbs:
  - create
