---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    toolkit.fluxcd.io/tenant: security
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: codecentric
  namespace: auth
spec:
  interval: 69m
  type: oci
  url: oci://ghcr.io/codecentric/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: auth
spec:
  releaseName: keycloak
  chart:
    spec:
      chart: keycloakx
      sourceRef:
        kind: HelmRepository
        name: codecentric
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    args:
      - "--verbose"
      - "start"
      - "--http-port=8080"
      - "--hostname-strict=false"
      - "--spi-events-listener-jboss-logging-success-level=info"
      - "--spi-events-listener-jboss-logging-error-level=warn"
    dbchecker:
      enabled: true
    database:
      vendor: postgres
      hostname: cnpg-db0-cluster-rw.dbs.svc.cluster.local
      port: 5432
      database: keycloak
      username: db0_keycloak
      existingSecret: db0-keycloak-user
      existingSecretKey: password
    extraEnv: |
      - name: KEYCLOAK_ADMIN
        valueFrom:
          secretKeyRef:
            name: {{ include "keycloak.fullname" . }}-admin-creds
            key: username
      - name: KEYCLOAK_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: {{ include "keycloak.fullname" . }}-admin-creds
            key: password
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: keycloak-password
  namespace: auth
spec:
  length: 32
  symbols: 0
  allowRepeat: true
  noUpper: false
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-keycloakx-admin-creds
  namespace: auth
spec:
  refreshInterval: 1h
  target:
    template:
      data:
        username: admin
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: keycloak-password
