---
apiVersion: v1
kind: Namespace
metadata:
  name: auth
  labels:
    toolkit.fluxcd.io/tenant: security
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: db0-keycloak-password
  namespace: dbs
spec:
  length: 64
  symbols: 0
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db0-keycloak-user
  namespace: dbs
spec:
  refreshInterval: 1h
  target:
    name: db0-keycloak-user
    template:
      data:
        username: keycloak
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: db0-keycloak-password
# Copy db0-keycloak-user secret to auth namespace. Suggest in future to use ExternalSecret to push the secret to auth namespace
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: codecentric
  namespace: auth
spec:
  interval: 69m
  type: oci
  url: oci://ghcr.io/codecentric/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: keycloak
  namespace: auth
spec:
  releaseName: keycloak
  chart:
    spec:
      chart: keycloakx
      sourceRef:
        kind: HelmRepository
        name: codecentric
  interval: 50m
  install:
    remediation:
      retries: 3
  values:
    database:
      vendor: postgres
      hostname: cnpg-db0-cluster-rw.dbs.svc.cluster.local
      port: 5432
      database: keycloak
      existingSecret: db0-keycloak-user
      existingSecreetKey: password
