---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: db0-keycloak
  namespace: dbs
spec:
  cluster:
    name: cnpg-db0-cluster
  name: db0-keycloak
  owner: db0_keycloak
  connectionLimit: 10
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: db0-keycloak-password
  namespace: dbs
spec:
  length: 64
  symbols: 0
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db0-keycloak-user
  namespace: dbs
spec:
  refreshInterval: 1h
  target:
    name: db0-keycloak-user
    template:
      data:
        username: keycloak
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: db0-keycloak-password
